### ISSUE TITLE
Performance problems with calls to Assembly::LoadFrom() from instrumented methods

### ISSUE THREAD

**Issue by mdomashchenko** [newrelic/newrelic-dotnet-agent#831] opened 2021-12-02 21:55 UTC
This call gets injected into the beginning of every instrumented method:
https://github.com/newrelic/newrelic-dotnet-agent/blob/813b8210523c2c50942df3da119f4008a86a25dd/src/Agent/NewRelic/Profiler/MethodRewriter/FunctionManipulator.h#L269

In our case `SqlCommand.ExecuteReaderAsync` and `HttpClient.SendAsync` which are executed constantly.

Unfortunately, that quickly hits this `lock` statement in `AssemblyLoadContext`
https://github.com/dotnet/runtime/blob/70d20f1445127d6473283047d0a551ccf85f897f/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L342

And looks like from time to time it's causing a lock convoy (https://devblogs.microsoft.com/oldnewthing/20061212-00/?p=28753)

I do have a dump file with 77 threads waiting on that `_unloadLock` object and no owner.

Could you, please, cache those types instead of loading them for every execution of every instrumented method?

**Comment by nr-ahemsath** [comment] 2021-12-03 18:47
This has a similar root cause to issue #533, which is currently marked closed, I believe pending feedback from the customer who was having the problem in that case.

Regarding caching the types, we do in fact do this for .NET Framework applications, but it just moves the problem somewhere else.

Ideally we should find a solution to this problem that works for both the framework and core versions of the agent.

**Comment by angelatan2** [comment] 2023-01-24 19:53
@mdomashchenko Thank you again for bringing this issue to our attention. We've spiked on the problem space; however, we will need more time to continue to hone in on the solution. An additional spike was created to have the devs continue to make forward progress.  We are closing this ticket as won't-fix until we have the spike resolved.  The spike is planned for this quarter.

**Closed by angelatan2** 2023-01-24 19:53 UTC
Labels: bug, community

**Comment by srilakshmiprasannaakkineni** [comment] 2023-06-13 18:18
Hello Team,

Is there any further progress on this issue? off late, we have been observing issues with our apps too.

**Comment by jaffinito** [comment] 2023-06-13 22:34
Thank you for checking in.  We have done additional research and believe we have an approach that would address the issue in .NET Framework. There is still some additional work needed to clean up the prototype and get it to production quality.  As for .NET Core/.NET, the approach we have in mind might also work, but since the two are very different we would need to dig in deeper with an additional spike.

We don't currently have the .NET Core/.NET spike or the .NET Framework prototype work scheduled, though it is on our radar.
