### ISSUE TITLE
Deduct duration of asynchronous child methods when they are known to be made synchronously

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#190] opened 2020-09-08 23:16 UTC
**Description**
A number of the methods we instrument in the frameworks we support are async methods. Generally speaking, we do not deduct the duration of async methods from the duration of the caller. Though for circumstances where we know the framework is effectively calling an async method synchronously (i.e., it blocks) we should consider deducting the time from the parent.

One such scenario is ASP.NET Web API. We instrument `ExecuteRequestHandler` that calls `System.Web.Http.Controllers.ApiControllerActionInvoker.InvokeActionAsync` which we also instrument. `InvokeActionAsync` is an async method, so the agent does not deduct its time from the time of `ExecuteRequestHandler`. Since we know `ExecuteRequestHandler` actually does block on `InvokeActionAsync` it probably makes sense to special-case these types of scenarios.

**Comment by vuqtran88** [comment] 2020-11-30 20:58
closing this issue because it's a duplicate of https://github.com/newrelic/newrelic-dotnet-agent/issues/93

**Closed by vuqtran88** 2020-11-30 20:58 UTC
Labels: bug
