### ISSUE TITLE
Possible memory leak in .net agent

### ISSUE THREAD

**Issue by kaluznyt** [newrelic/newrelic-dotnet-agent#1988] opened 2023-10-18 10:08 UTC
We're seeing an increasing number of objects related to New Relic in our .net core app.

**Description**
Took a couple of memory dumps of a .net core app (running on kubernetes) and seeing an increasing number of objects from newrelic.agent namespace like: 
MethodCallData
Segment
ParsedSqlStatement
ConnectionInfo
DataStoreSegmentData

Which is causing the application to hit the OOM when it's running for couple of days.

**Expected Behavior**
Not seeing a constant increase in memory used caused by the new relic objects

**Steps to Reproduce**
No particular steps required.

**Your Environment**
[TIP]:  # ( Describe your environment, please include the running version of the agent, .NET Framework, .NET Core, or .NET versions, and any relevant configurations)
.NET Core API app running on Kubernetes, .NET Core 6, NewRelic agent version 10.17.0
<img width="642" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/572605/55a79d7b-4b13-499c-95fd-2fab467ecb51">

Those screenshots are from dotMemory, dumps taken from the same container 1 day apart:
<img width="588" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/572605/76423d47-2151-4364-867c-88e49a3e4ba5">
<img width="808" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/572605/3bf75ea9-e9aa-41e3-8bcc-af5030cd482b">

**Comment by nrcventura** [comment] 2023-10-18 16:58
Thank you for reporting this to us. The datatypes that you are reporting in this issue and in the screenshots are datatypes that we expect to see created for every single call to a database/datastore. 

- MethodCallData is an object that is created for every single call to an instrumented method
- Segment is an object that typically represents a method call within a transaction
- ParsedSqlStatement is an object that is created for each database/datastore call
- ConnectionInfo is an object that is created for each database/datastore call
- DatastoreSegmentData is an object that is created for each database/datastore call

In general, this data should only be considered alive until a transaction ends and is transformed into the wire models that are stored in reservoirs until they are ready to be transmitted to New Relic. The agent does have some caching in place for ParsedSqlStatement which can keep those instances alive longer.

We will need more information to better understand what is happening. Information like the following can help us understand what is going on.

1. How many database calls do you expect to see per transaction?
2. How many transactions do you expect to see executing concurrently?
3. Do you have a shareable reproduction of this memory problem?

**Comment by kaluznyt** [comment] 2023-10-19 06:56
Thanks for your reply. 

Ok, basically, the app mostly calls the Redis via the StackExchange.Redis multiplexers (cached/singletons). It calls different instances of Redis (like one hosted in the cloud, one in kubernetes itself).

It calls SQL Server, but that's small percentage of whole db traffic.

In terms of database calls, difficult to tell it really dependes on the request, but usually multiple calls are going out to Redis per Transaction/Request, however, there are many concurrent requests, I would say the traffic is quite high all the time.

As for the reproduction, I don't have anything at the moment, we're seeing this on live environment.  Perhaps I'll try it. Or maybe I could run some new relic instrumentation if that can help anyhow ?

**Comment by kaluznyt** [comment] 2023-10-19 07:05
So this is the breakdown in the sample transaction from New Relic: 
<img width="1706" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/572605/e4b4e337-7035-4882-83b3-869ad4dc5fa4">

**Comment by kaluznyt** [comment] 2023-10-19 07:09
And this is dump from the same pod, but from today, we see a large increase in the objects counts compared to previous dumps: 
<img width="862" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/572605/8fac68c9-d36e-43b9-87a3-665d12f70859">

**Comment by kaluznyt** [comment] 2023-10-19 07:10
Is the ParsedSqlStatement used for Redis, or only for the SQL Queries ? From the name I suppose only for SQL Queries, perhaps that's somewhere we should look into ?

**Comment by kaluznyt** [comment] 2023-10-19 07:22
I just took a look into one of the ParsedSqlStatement objects, and seems it's redis related: 
<img width="597" alt="image" src="https://github.com/newrelic/newrelic-dotnet-agent/assets/572605/f93f55f2-b7c5-40d1-8cbf-6e6d1a9afdaf">

**Comment by nrcventura** [comment] 2023-10-19 17:15
That definitely seems like a memory leak. Since you can find that transaction in the New Relic UI, the transaction probably ended and got transformed, which would allow the garbage collector to reclaim that memory. However, it's possible that it is being referenced on another thread and being kept in memory. This may be a side-effect of how the agent maintains state by leveraging AsyncLocal storage to allow the transaction to flow with all of the async thread hops that a transaction/request may go through. Things like starting a timer, and certain ways of kicking off async background work can cause AsyncLocal state to be captured even though that async work is not part of the request.

To further help you we will either need an application that we can use to reproduce the problem. Or you may need to work with our support team in order to share the memory dump with us and possibly some sample code. By working with our support team you can avoid sharing potentially sensitive information on github. For more information on our support team you can refer to [Support Options](https://github.com/newrelic/newrelic-dotnet-agent#support). If you open a request with the support team please reference this github issue so that we can ensure that the issues are linked together.

**Comment by kaluznyt** [comment] 2023-10-20 10:58
Thank you for directing us. We'll try to investigate what can be the cause based on your input, if we cannot figure it out, we'll open a support request to get help.

**Comment by nrcventura** [comment] 2023-10-23 17:58
I'm closing this ticket for now. If a support request is opened for this, we will address the problem through the support process. If more information becomes available, and we can identify or reproduce the problem, we can reopen the ticket later.

**Closed by nrcventura** 2023-10-23 17:58 UTC
Labels: bug, community
