### ISSUE TITLE
New relic TraceId Not getting poplulated in .net core middleware

### ISSUE THREAD

**Issue by cpr4377** [newrelic/newrelic-dotnet-agent#2707] opened 2024-08-22 14:14 UTC
New relic TraceId Not getting poplulated in .net core middleware.

**Description**
I am trying to access the newrelic traceid in asp.net core middleware and pass it as a response header in the response.

Please see the implementation below :
```
`public sealed class TraceIdMiddleware
{
       private readonly RequestDelegate _next;
       private readonly ILogger<TraceIdMiddleware> _logger;

   public TraceIdMiddleware(RequestDelegate next, ILogger<TraceIdMiddleware> logger)
   {
       _next = next;
       _logger = logger;
   }

   public async Task InvokeAsync(HttpContext context)
   {
       if (!context.Request.Headers.ContainsKey("X-Trace-Id"))
       {
           var tracer = NewRelic.Api.Agent.NewRelic.GetAgent();
           var traceId = tracer.TraceMetadata.TraceId;
           
           _logger.LogWarning("NewRelic Trace Id " + traceId);
           _logger.LogWarning("Http context trace Id " + context.TraceIdentifier);
         
           if (!string.IsNullOrEmpty(traceId))
           {
               context.Response.Headers.Append("X-Trace-Id", traceId);
           }
       }
       await _next(context);
   }
   }`
```

But the trace id is always coming as empty . The agent is running and distributed tracing is enabled, still the issue persist. Has anyone encountered this issue ?

**Expected Behavior**
Traceid should not be coming empty

Using the latest agent and latest donet newrelic api

**Comment by tippmar-nr** [comment] 2024-08-22 19:00
Thanks @cpr4377 for your bug report. 

I created a simple test app targeting .NET 8 (using the default Web API app from Visual Studio), added your middleware code and ran some tests. The NewRelic trace id was generated for each request:

![image](https://github.com/user-attachments/assets/4c13fb6b-e117-429e-a36f-c3be52a0b57b)

How are you adding the middleware to the asp.net core request pipeline? The .NET agent injects our middleware at the very beginning of the request pipeline, so if you're doing anything other than just calling `app.UseMiddleware<TraceIdMiddleware>()`, it's possible you're interfering with the agent's middleware injection. 

I'm going to close this bug since I can't reproduce it, but if you have further information that would help reproduce it, feel free to re-open and provide a repro app.

**Closed by tippmar-nr** 2024-08-22 19:00 UTC
Labels: bug, community
