### ISSUE TITLE
Integration Tests - for Infinite Tracing (8T)

### ISSUE THREAD

**Issue by angelatan2** [newrelic/newrelic-dotnet-agent#147] opened 2020-08-25 14:56 UTC
### Is your feature request related to a problem? Please describe.
No

### Feature Description
Add integration test for 8T

### Describe Alternatives
N/A

### Additional context
Add to CI
Originated from DOTNET4618
Reporter: Jason Feingold

### Priority
[Nice to Have, <strike>Really Want, Must Have, Blocker</strike>]

**Comment by nr-ahemsath** [comment] 2021-01-04 22:30
I ended up creating a duplicate of this issue with issue #415.  However, that issue contains more details about implementation, so I'm going to close this issue.

**Closed by nr-ahemsath** 2021-01-04 22:30 UTC
Labels: testing
