### ISSUE TITLE
Environment variables are not applied when running in a container

### ISSUE THREAD

**Issue by storey247** [newrelic/newrelic-dotnet-agent#2622] opened 2024-07-12 14:05 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**

When running the APM Agent in a container along with our application, setting environment variables such as `NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES` do not get applied. 

We are running our container image in AWS ECS and we set the task definition with the env variable `NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES` set to be `"422"` but the errors are still reported by the agent into the NR application.

**Expected Behavior**

When the environment variable is set in the container runtime then the APM agent should take those settings into account

**Steps to Reproduce**

- Create an container spec file that installs the NR APM agent and a .NET api as the entrypoint
- Start the container setting env var `NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES`
- When application returns an error code you expect to be ignored, it will appear in the app error inbox incorrectly

**Your Environment**

- .NET8 
- Containers

**Additional context**
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**For Maintainers Only or Hero Triaging this bug**
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by nr-ahemsath** [comment] 2024-07-12 16:42
Thank you for submitting this issue.  In order to troubleshoot this, we might require you to send us agent log files and/or other details about your app and its environment, as well as your New Relic account.  Public Github might not be the best place for this due to privacy concerns.  Do you have the ability to open a case with New Relic support?  If so, please do that and mention this Github issue in the case.

**Comment by nr-ahemsath** [comment] 2024-08-01 20:38
@storey247 I attempted to reproduce the issue you described, and I did not see any problems.  In my testing, the agent behaved as expected.  See https://github.com/newrelic/newrelic-dotnet-examples/tree/main/ignore-errors for the containerized test app I used and the testing procedure I followed.

Can you try testing using that example and let me know what happens?

**Comment by storey247** [comment] 2024-08-01 21:25
Hi @nr-ahemsath thanks and yes we can confirm that this approach does indeed work. 

The problem is we are using a multi stage dockerfile where we install the agent and its env vars/setup into a base image. We did this in an attempt to simplify the necessity to have all the boilerplate in all our dockerfiles. 

If we then use that base image, copy in our .NET binary set the env var for ignore error code and expose port we see the ignore error code not being honoured correctly.

**Comment by nr-ahemsath** [comment] 2024-08-02 18:25
@storey247 When your application is running, can you check in the APM UI to see whether the env var is being picked up by the agent?  If you go to `Environment->Agent Initialization` and look at the value of `error_collector.ignore_status_codes`, whatever code(s) you are setting via the env var should show up in the UI:

![Screenshot 2024-08-02 112108](https://github.com/user-attachments/assets/1ad37c72-a82f-49de-bcd3-bb916d95053b)

**Comment by storey247** [comment] 2024-08-21 13:12
Apologies, i forgot to cycle back round to this, i need to spin up some infrastructure to validate the question asked @nr-ahemsath please bear with me

**Comment by chynesNR** [comment] 2024-09-06 17:49
Hi @storey247 -- since there isn't anything for us to do at the moment, I'm going to close this ticket, but please feel free to reopen it or file a new one if you still have questions. Thanks!

**Closed by chynesNR** 2024-09-06 17:49 UTC
Labels: bug, community
