### ISSUE TITLE
Agent fails to enable infinite tracing in net5.0 docker images

### ISSUE THREAD

**Issue by amweiss** [newrelic/newrelic-dotnet-agent#394] opened 2020-12-16 15:12 UTC
**Description**
With the official .net 5.0 images, infinite tracing is broken and doesn't report data but standard tracing does.

**Expected Behavior**
After enabling infinite tracing, the tracing data is sent to the edge observer.

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**

```
2020-12-16 14:57:42,368 NewRelic  DEBUG: [pid: 8, tid: 18] SpanStreamingService: Error creating gRPC channel to endpoint <redacted>. (attempt 0)  - Exception: NewRelic.Agent.Core.DataTransport.GrpcWrapperException: Unable to create new gRPC Channel 
 ---> System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory 
   at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags) 
   at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg) 
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives) 
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary() 
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods() 
   at Grpc.Core.Internal.NativeExtension..ctor() 
   at Grpc.Core.Internal.NativeExtension.Get() 
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit() 
   at Grpc.Core.GrpcEnvironment..ctor() 
   at Grpc.Core.GrpcEnvironment.AddRef() 
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options) 
   at NewRelic.Agent.Core.DataTransport.GrpcWrapper`2.CreateChannel(String host, Int32 port, Boolean ssl, Metadata```
```

**Steps to Reproduce**
Setup any application with a base docker image of `mcr.microsoft.com/dotnet/aspnet:5.0.1` and try to enable infinite tracing.

**Your Environment**
Docker container based on `mcr.microsoft.com/dotnet/aspnet:5.0.1`

**Additional context**

**Comment by vuqtran88** [comment] 2020-12-18 18:54
@amweiss
Thanks for reporting the problem to us. Out of curiosity, I wonder if you published your application as a single file by any chance. There is currently a bug with grpc in .NET 5 with a workaround that might be related to this problem, https://github.com/grpc/grpc/issues/24266

**Comment by amweiss** [comment] 2020-12-18 19:02
Unfortunately not, it is just a standard aspnet app in docker.

It's build with `mcr.microsoft.com/dotnet/sdk:5.0.101` and run in `mcr.microsoft.com/dotnet/aspnet:5.0.1` with an entry point like: `dotnet Name.Service.dll`.

**Comment by vuqtran88** [comment] 2020-12-21 19:37
@amweiss 
Thanks for confirming. We will prioritize this bug and hopefully fix it soon.

**Comment by vuqtran88** [comment] 2020-12-22 18:24
@amweiss
I had a chance to test out the `mcr.microsoft.com/dotnet/sdk:5.0.101` and `mcr.microsoft.com/dotnet/aspnet:5.0.1` docker images with a vanilla asp.net 5.0 app with infinite tracing enabled. I could not get the exception that you are seeing. This is the content of the Dockerfile that I'm testing. 

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0.101 AS build
WORKDIR /src
COPY ["InfiniteTraceDemo/InfiniteTraceDemo.csproj", "InfiniteTraceDemo/"]
RUN dotnet restore "InfiniteTraceDemo/InfiniteTraceDemo.csproj"
COPY . .
WORKDIR "/src/InfiniteTraceDemo"
RUN dotnet build "InfiniteTraceDemo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "InfiniteTraceDemo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_NEWRELIC_HOME=C:/app/newrelic
ENV CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
ENV CORECLR_PROFILER_PATH=C:/app/newrelic/NewRelic.Profiler.dll
ENV NEW_RELIC_APP_NAME=_YOUR_APP_NAM_
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
ENV NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST=_YOUR_TRACE_OBSERVER_URL_
ENV NEW_RELIC_LICENSE_KEY=_YOUR_LICENSE_KEY_

ENTRYPOINT ["dotnet", "InfiniteTraceDemo.dll"]
```

Would you mind share us how did you set up your docker image ? Also, how did you install the .NET agent ? For my test application, I installed the agent via the `NewRelic.Agent` nuget package.

**Comment by amweiss** [comment] 2021-01-04 18:02
@vuqtran88 We used the nuget package as well, but the base image is from Debian 10, not Windows, so I'm not sure your example worked with `C:/app/newrelic` and `C:/app/newrelic/NewRelic.Profiler.dll` can you confirm you saw metrics being recorded with that running? It should be something more like `/app/newrelic` and `/app/newrelic/libNewRelicProfiler.so`

**Comment by vuqtran88** [comment] 2021-01-04 21:47
@amweiss
Thanks for the extra information. I'm able to repro this. The issue is only particular to Linux container. I didn't see the issue happened in Windows container (as you pointed out in my previous repro attempt). This issue is related to this Microsoft issue https://github.com/grpc/grpc/issues/24153 which has already been fixed in the `Grpc.Core` nuget package version `2.34.0`. Our .Net agent is currently depending on the `Grpc.Core` version `2.28.1` and it is  ILRepacked. We need to update the version of the `Grpc.Core` to `2.34.0` in our agent.

There is a workaround which I confirm it works. You can add the following command in your Dockerfile at the image that will be used to host your app:
`RUN apt-get update && apt-get install -y libc-dev && apt-get clean`

**Comment by vuqtran88** [comment] 2021-01-12 01:55
Reopens this issue as the fix in https://github.com/newrelic/newrelic-dotnet-agent/pull/416 broke infinite tracing functionality.

@amweiss I am sorry for the inconvenience. I might have to revert the PR that you submitted. We will continue to find a solution for this issue. In the mean time, please use the workaround as I mentioned in my previous comments.

**Closed** 2021-02-05 01:55 UTC
Labels: bug, community, question
